# Generated by Django 4.0.5 on 2022-07-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombreAlumno', models.CharField(max_length=50, verbose_name='Nombre del Alumno')),
                ('grupo', models.CharField(max_length=50, verbose_name='Grupo')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('nota', models.TextField(verbose_name='Nota')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Subido')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Entregable',
                'verbose_name_plural': 'Entregables',
                'ordering': ['created'],
            },
        ),
    ]
