# Generated by Django 4.0.5 on 2022-07-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_entregables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.CharField(max_length=50, verbose_name='Nombre del Padre')),
                ('nombreA', models.CharField(max_length=50, verbose_name='Nombre del Alumno')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('grupo', models.CharField(max_length=50, verbose_name='Grupo')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('duda', models.TextField(verbose_name='Duda')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Subido')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['created'],
            },
        ),
    ]
